In [1]:
import numpy as np
import pandas as pd

1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [11]:
N=10
np.array(list(reversed(range(N))))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [19]:
N=6
diag_matrix = np.diag(list(reversed(range(N))))
print(diag_matrix)
np.trace(diag_matrix)

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


15

3. Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [111]:
import os
data = pd.read_csv(os.path.join(os.getcwd(), r'Python-5\ml-latest-small\ratings.csv'))

topmovieId, rating = data[ ['movieId', 'rating'] ] [data['rating'] == 5.0].groupby('movieId', as_index=False).count().sort_values('rating', ascending=False).iloc[0]

movies = pd.read_csv(os.path.join(os.getcwd(), r'Python-5\ml-latest-small\movies.csv'))
movies[movies['movieId'] == topmovieId]


movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

4. По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [ ]:
data = pd.read_csv(os.path.join(os.getcwd(), r'Python-5\power.csv'))

In [140]:
filtered_data = data[ 
    ( (data['country']=='Latvia') | (data['country']=='Lithuania') | (data['country']=='Lithuania') ) &
    ( data['category'].isin([4,12,21]) ) &
    ( data['year'].between(2005, 2010, inclusive=True) ) &
    ( data['quantity'] > 0 )
]
filtered_data.info()

filtered_data['quantity'].sum()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266 entries, 11156 to 253986
Data columns (total 4 columns):
country     266 non-null object
year        266 non-null int64
quantity    266 non-null float64
category    266 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 10.4+ KB


177140.0

5. Решите систему уравнений
\begin{equation*}
4x + 2y + z = 4 \\
x + 3y = 12 \\
5y + 4z = -3
\end{equation*}

In [5]:
a = np.array(([4,2,1], [1,3,0], [0,5,4]))
b = np.array([4,12,-3])
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [6]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True