In [2]:
import numpy as np

1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [11]:
N=10
np.array(list(reversed(range(N))))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [19]:
N=6
diag_matrix = np.diag(list(reversed(range(N))))
print(diag_matrix)
np.trace(diag_matrix)

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


15

3. Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

4. По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

5. Решите систему уравнений
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3